### ISSUE TITLE
Time conversion - split instead of total used

### ISSUE THREAD

**Issue by tchaloupka** [kaleidicassociates/influx-d#10]
Sorry to bother again :)

But I thing that there should be used total instead of split here: https://github.com/kaleidicassociates/influx-d/blob/master/source/influxdb/api.d#L203

If I understand it correctly, split will drop the higher order values, so it will drop msecs and usecs and only return nsecs.

**Comment by atilaneves** [comment]
I modified an existing unit test and it passed without changes - meaning that `split` and `total` did the same thing for what I'm using it for. I ended up commiting anyway since `total` is cleaner, but all in all this wasn't really needed.

In the future please make sure it's actually a bug and you have a reproducible test case. Or, better yet, since you knew what change to make, submit a PR. Thanks.
